### ISSUE TITLE
Piwigo-BatchDownloader with PHP 7.2

### ISSUE THREAD

**Issue by JohnBluebear** [Piwigo/Piwigo-BatchDownloader#23]
Piwigo BatchDownloader works very well with Piwigo 2.9.4 and PHP 7.1.

But if I switch to PHP 7.2, I get the error message "plugins/BatchDownloader/admin/config.php on line 45".

Any ideas?

**Comment by f3red** [comment]
I have a similar problem, after updating Piwigo 2.9.4 and PHP 7.2. When downloading a batch of files, I am getting the following messages for every file:

![capture](https://user-images.githubusercontent.com/41441173/42950022-f9469196-8b27-11e8-807a-398673616cd8.JPG)

Let me hasten to add that it appears the download performs successfully, but it concerns me, as well as our site users.

**Comment by dhui** [comment]
Looks like `create_function()` was [deprecated in PHP 7.2](http://php.net/manual/en/migration72.deprecated.php#migration72.deprecated.create_function-function). Replacing `create_function()` with `function()` should work.
