### ISSUE TITLE
no compatibility with PHP 8.1

### ISSUE THREAD

**Issue by Ilav1** [Piwigo/Piwigo-BatchDownloader#42]
When Piwigo 13 launched, I updated PHP to 8.1.
After the Update there are some Errors when I go into an album:

![1](https://user-images.githubusercontent.com/102852954/196046335-f8b38cb0-25a0-466a-92a4-d2011bf896cc.png)

at the top of EVERY page this error appears

![2](https://user-images.githubusercontent.com/102852954/196046371-f48f70c1-91c3-43d5-81a9-b79d941beb51.png)

**Comment by Ilav1** [comment]
Some errors also appear on the BatchDownloader settings page

![3](https://user-images.githubusercontent.com/102852954/196047695-2253a38b-8401-41f5-8191-66f03b320d24.png)

**Comment by mossroy** [comment]
Same here on all pages of the album:
![image](https://user-images.githubusercontent.com/890923/203153633-cba0ed0f-5197-4995-8c2e-ec8b037894dc.png)

(I don't see any issue in the settings page)

Using PHP 8.0.25

**Comment by robinofe** [comment]
i have the same issues on all gallerypages: 
![image](https://user-images.githubusercontent.com/86108619/203444301-e7b3fa2b-96d1-44dd-b853-eef921d7c014.png)

and on the settings page of the plugin:
![chrome_4mFbhYShrK](https://user-images.githubusercontent.com/86108619/203444356-ca7db411-9d94-48e3-b81c-171c9d700469.png)

PHP Version: 8.0.25

**Comment by e-dschungel** [comment]
Same issue here with PHP 8.1.13, #43 is a duplcate.

The issue is that 
`<a href="{$BATCH_DWN_URL}{$BATCH_DWN_SIZE}" id="batchDownloadLink" title="{'Download all pictures of this selection'|translate}" class="pwg-state-default pwg-button" rel="nofollow">` is compiled to `
<a href="<?php echo $_smarty_tpl->tpl_vars['BATCH_DWN_URL']->value;
echo $_smarty_tpl->tpl_vars['BATCH_DWN_SIZE']->value;?>
" id="batchDownloadLink" title="<?php echo l10n('Download all pictures of this selection');?>
" class="pwg-state-default pwg-button" rel="nofollow">
` so that a warning is issued if $BATCH_DWN_SIZE is not defined since PHP8.

#44 should fix it, but please check if given defaults make sense.

**Comment by Ilav1** [comment]
@e-dschungel I tried your change and I think its working fine. There are no warings anymore.

Today I created a BatchDownload and got many other warnings. The Download is working fine.
I don´t know if the warnings are shown before. This is my first BatchDownload:

Warning: Undefined array key "missing_derivatives" in /var/www/html/piwigo/_data/templates_c/1hjw97b^85e8d51a46e27d55e1e92bfce90ea14c7deeedcf_0.file.init_zip.tpl.php on line 47

Warning: Attempt to read property "value" on null in /var/www/html/piwigo/_data/templates_c/1hjw97b^85e8d51a46e27d55e1e92bfce90ea14c7deeedcf_0.file.init_zip.tpl.php on line 47

Warning: Undefined array key "elements_error" in /var/www/html/piwigo/_data/templates_c/1hjw97b^85e8d51a46e27d55e1e92bfce90ea14c7deeedcf_0.file.init_zip.tpl.php on line 141

Warning: Attempt to read property "value" on null in /var/www/html/piwigo/_data/templates_c/1hjw97b^85e8d51a46e27d55e1e92bfce90ea14c7deeedcf_0.file.init_zip.tpl.php on line 141

Warning: Undefined array key "U_EDIT_SET" in /var/www/html/piwigo/_data/templates_c/1hjw97b^85e8d51a46e27d55e1e92bfce90ea14c7deeedcf_0.file.init_zip.tpl.php on line 144

Warning: Undefined array key "SIZE_INFO" in /var/www/html/piwigo/_data/templates_c/1hjw97b^85e8d51a46e27d55e1e92bfce90ea14c7deeedcf_0.file.init_zip.tpl.php on line 152

Warning: Undefined array key "missing_derivatives" in /var/www/html/piwigo/_data/templates_c/1hjw97b^85e8d51a46e27d55e1e92bfce90ea14c7deeedcf_0.file.init_zip.tpl.php on line 167

Warning: Attempt to read property "value" on null in /var/www/html/piwigo/_data/templates_c/1hjw97b^85e8d51a46e27d55e1e92bfce90ea14c7deeedcf_0.file.init_zip.tpl.php on line 167

Warning: Undefined array key "U_CANCEL" in /var/www/html/piwigo/_data/templates_c/1hjw97b^85e8d51a46e27d55e1e92bfce90ea14c7deeedcf_0.file.init_zip.tpl.php on line 195

![2023-04-15 12_01_00](https://user-images.githubusercontent.com/102852954/232207279-1547b685-b877-4e19-903a-dd524dc822ba.png)


![2023-04-15 11_48_19-](https://user-images.githubusercontent.com/102852954/232206929-d703aefb-70ad-4ae2-b6bc-55a9d564ef08.png)

**Comment by e-dschungel** [comment]
@Ilav1: Thanks for your  report. The underlying issue is the same. Amended #44 with a fix for that.

@plegall: Please check the PR and merge the changes if everything is fine.

**Comment by plegall** [comment]
@e-dschungel fixes released in version 13.a

**Comment by SillyPilleus** [comment]
@e-dschungel Sorry to open a closed issue, but I have the same error message as one of the posts above and wandered if the issue was the same...

The error I get is:

Warning: Undefined array key "SIZE_INFO" in /config/www/_data/templates_c/ljbwkp^ca02ba530b0cd12685a15d4a96e31fabd5fd5493_0.file.init_zip.tpl.php on line 153

And I can't download anything, I just get a blank page.

Any help gratefully received!

**Comment by SillyPilleus** [comment]
> @e-dschungel Sorry to open a closed issue, but I have the same error message as one of the posts above and wandered if the issue was the same...
> 
> The error I get is:
> 
> Warning: Undefined array key "SIZE_INFO" in /config/www/_data/templates_c/ljbwkp^ca02ba530b0cd12685a15d4a96e31fabd5fd5493_0.file.init_zip.tpl.php on line 153
> 
> And I can't download anything, I just get a blank page.
> 
> Any help gratefully received!

Have just seen there's a pull request to fix this - https://github.com/Piwigo/Piwigo-BatchDownloader/pull/56
Tested the changed files in the request and it works great.

**Comment by e-dschungel** [comment]
@plegall: please check and merge #56
