### ISSUE TITLE
Télécharger aussi les sous albums

### ISSUE THREAD

**Issue by lipki** [Piwigo/Piwigo-BatchDownloader#9]
Bonjour,
J'aimerais pouvoir télécharger les sous-albums comme dossier.

Je crois avoir tout dit :)

(je jetterais un œil pour créer l'option au cas ou.)

**Comment by mistic100** [comment]
Bonjour,
ça serait une super fonction, mais je ne fais plus de dev PHP...

je ne sais même plus si le plugin va chercher les sous-albums et applatit tout ou s'il les ignore.

les pull requests sont les bienvenues :-)

**Comment by lipki** [comment]
arf zut ...

Pour info le plugin ignore les sous-albums.

**Comment by plegall** [comment]
Affichage "flat" et téléchargement par lot, ça marche très bien.

**Comment by mistic100** [comment]
@plegall ça ne créé pas de dossiers dans le zip si ?

**Comment by plegall** [comment]
en effet, évidemment si on bascule en flat, il n'y a plus de sous-dossiers à l'affichage, ni dans l'archive. Pour moi c'est déjà bien (et acceptable)
